# Generated by Django 4.2.7 on 2024-10-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='url',
            new_name='image',
        ),
    ]
