# Generated by Django 4.2.7 on 2024-11-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='name',
            new_name='vacancy_name',
        ),
    ]
