# Generated by Django 4.2.7 on 2024-10-20 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='formed_at',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='moderator',
        ),
        migrations.AddField(
            model_name='responses',
            name='disability',
            field=models.TextField(blank=True, null=True, verbose_name='Особенности инвалидности'),
        ),
        migrations.AddField(
            model_name='responses',
            name='resume',
            field=models.TextField(blank=True, null=True, verbose_name='Описание достижений'),
        ),
        migrations.AddField(
            model_name='responses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='responses',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vacancies'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='responses',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
