# Generated by Django 4.2.7 on 2024-10-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='name_human',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='status',
            field=models.IntegerField(choices=[(1, 'Черновик'), (2, 'Удалена'), (3, 'Сформирована'), (4, 'Завершена'), (5, 'Отклонена')], default=1),
        ),
    ]
