# Generated by Django 4.2.7 on 2024-10-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_vacancies_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='image',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
