# Generated by Django 4.2.7 on 2024-10-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_responses_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
    ]
