# Generated by Django 4.2.7 on 2024-10-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_responses_name_human_alter_responses_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responses',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responses',
            name='peculiarities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
