# Generated by Django 4.2.7 on 2024-12-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_vacancies_vacancy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='vacancies',
            field=models.ManyToManyField(blank=True, through='app.ResponsesVacancies', to='app.vacancies'),
        ),
    ]
