# Generated by Django 4.2.7 on 2024-10-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_url_vacancies_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='formed_at',
            new_name='deleted_at',
        ),
    ]
