# Generated by Django 4.2.7 on 2024-10-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_responses_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='vacancy_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
