# Generated by Django 4.2.7 on 2024-10-22 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_peculiarities_responses_peculiarities_comm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='id_vacancies',
            new_name='id_vacancy',
        ),
        migrations.RenameField(
            model_name='vacancies',
            old_name='image',
            new_name='url',
        ),
    ]
