# Generated by Django 4.2.7 on 2024-12-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_id_vacancy_vacancies_vacancy_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='image',
            new_name='url',
        ),
    ]
