# Generated by Django 4.2.7 on 2024-10-20 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_remove_responses_city_remove_responses_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
