# Generated by Django 4.2.7 on 2024-10-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_responses_created_at_alter_responses_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='status',
            field=models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1),
        ),
        migrations.AlterField(
            model_name='responses',
            name='status',
            field=models.IntegerField(choices=[(1, 'Черновик'), (2, 'Удалена'), (3, 'Сформирована'), (4, 'Завершена'), (5, 'Отклонена')], default=1),
        ),
    ]
