# Generated by Django 4.2.7 on 2024-10-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_vacancies_status_alter_responses_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='name_human',
            field=models.TextField(blank=True, null=True),
        ),
    ]
